### ISSUE TITLE
Fix Requires-spl syntax

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs-buildbot#27]
After submitting a PR with the `Requires-spl:` keyword all subsequent build requests will use the same SPL commit instead of defaulting back to master.  Restarting the build master resets the SPL dependency and is the current work around the issue.

**Comment by dinatale2** [comment]
I believe the issue is with `ss = self.codebases[codebase]` in `CustomSingleBranchScheduler.getCodebaseDict`. I believe ss is a shallow copy of the dictionary pulled from self.codebases.

There are copy tools in python that can be used to make a deep copy. I'll make a pull request shortly. I'm not sure how we would be able to actually test it though.

**Comment by behlendorf** [comment]
@dinatale2 if you can propose a patch I'm sure we can find some idle time on the buildbot to put it in place for testing.
